# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release - Tag, Release, Publish and Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: Tag name
        required: false
        type: string
      skip-npm:
        description: Skip npm publish
        required: false
        type: boolean

env:
  node_version: 20.x
  pnpm_version: 8.x

jobs:
  release:
    name: Tag and release commit
    runs-on: ubuntu-latest

    outputs:
      tag-name: ${{ steps.push-tag.outputs.tag_name }}
      commit-hash: ${{ steps.push-tag.outputs.commit_hash }}

    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Setup pnpm ${{ env.pnpm_version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm_version }}

      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: install dependencies
        run: |
          # ================= Install =================

          pnpm install

      - name: Release
        run: |
          # ================= Release =================

          # setup git credentials
          git config user.name "GitHub Release Bot"
          git config user.email "<>"

          # generate release
          pnpm run release

      - name: Push to remote
        id: push-tag
        run: |
          # ================= Remote =================

          # Check status
          git status
          git diff --color -U0 | cat

          # push changes
          git push origin --follow-tags
          
          tag_name=$(git describe --abbrev=0 --match 'v*')
          commit_hash=$(git rev-parse HEAD)
          
          echo "Pushing tag: ${tag_name}"
          echo "Pushing commit: ${commit_hash}"
          
          echo "tag_name=${tag_name}" >> "$GITHUB_OUTPUT"
          echo "commit_hash=${commit_hash}" >> "$GITHUB_OUTPUT"

  publish:
    name: Publish
    needs: release
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      commit-hash: ${{ needs.release.outputs.commit-hash }}
      tag-name: ${{ inputs.tag-name || needs.release.outputs.tag-name }}
      skip-npm: ${{ inputs.skip-npm }}

  deploy:
    name: Deploy
    needs: publish
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
